### ISSUE TITLE
Trouble loading

### ISSUE THREAD

**Issue by exnx** [moaljazaery/TinyFaces-Face-Detector-TF#1]
Hi, I was having trouble running your code.

The argument: --weight_file_path  /path/to/pickle_file, does this just point to the output directory, or does this point to another file we need to download somewhere?  I'm not sure where to find it.

Also, if just a directory for output, I get the following error:

Traceback (most recent call last):
  File "matconvnet_hr101_to_pickle.py", line 29, in <module>
    f = sio.loadmat(args.matlab_model_path)
  File "/Users/tvision/Desktop/TinyFaces-Face-Detector-TF/tiny-env/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/Users/tvision/Desktop/TinyFaces-Face-Detector-TF/tiny-env/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "/Users/tvision/Desktop/TinyFaces-Face-Detector-TF/tiny-env/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: 'files.mat'

**Comment by moaljazaery** [comment]
it looks like you have problem with the input .mat file (No such file or directory: 'files.mat')

Follow "Converting a pretrained model" section in the read me. If doesn't work I will share the final pkl file with you

**Comment by exnx** [comment]
I was able to convert it!  I had to use this command and it worked:
python matconvnet_hr101_to_pickle.py --matlab_model_path ./hr_res101.mat --weight_file_path ./hr_res101.pkl

**Comment by exnx** [comment]
However, now I have another unicode error, which I'm not sure where the bad character is or why:

Traceback (most recent call last):
  File "tiny_face_eval.py", line 227, in <module>
    main()
  File "tiny_face_eval.py", line 224, in main
    lw=args.line_width, display=args.display)
  File "tiny_face_eval.py", line 82, in evaluate
    model = tiny_face_model.Model(weight_file_path)
  File "/Users/tvision/Desktop/Tiny_Faces_in_Tensorflow/tiny_face_model.py", line 23, in __init__
    self.mat_blocks_dict, self.mat_params_dict = pickle.load(f)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 112: invalid continuation byte

**Comment by moaljazaery** [comment]
I am not sure about this. Maybe try different python version, or upgrade your python packages

**Comment by exnx** [comment]
Rats, I tried a different python version (anaconda) but it still didn't work.

**Comment by moaljazaery** [comment]
I uploaded the converted weights, hope this can help:
https://drive.google.com/open?id=1m8dcxNdFAH75Q5BSvyVXeVlerSS0y0LE

**Comment by Gaurav14cs17** [comment]
@moaljazaery  i can't  access this link
plz upload this weight in yr Git idee

**Comment by moaljazaery** [comment]
Sorry, the link access setting was wrong. Try now!
